### ISSUE TITLE
Love a link to your code from AngularConnect

### ISSUE THREAD

**Issue by aaronfrost** [grant/talks#3]
At AngularConnect, you made it so that when the side bar is shown, you could click any cell and it would update the side bar with the data for that row. I want to do that.

I can't figure out how to respond to when a cell is clicked with Apps Script. Can you please provide your code sample for that talk here so that I can see it and use it as a reference?

**Comment by grant** [comment]
Hey I’ll respond with more info after thanksgiving.

**Comment by aaronfrost** [comment]
I figured it out. In the html on the client, you have to do a setInterval to call `google.script.run.blah` and get the data from the server that way It isn't as easy as I had expected, but it works. 

Is there a limit to how many of those requests you can make a day?

**Comment by grant** [comment]
Yeah. I do that. There’s no limit afaik. But be careful of using APIs because you’ll quickly run into limits. Don’t make calls if the cell selection hasn’t been updated.
